enclave-server-arm:
	docker build --build-arg TARGETPLATFORM=aarch64-unknown-linux-musl -t enclave-server -f Dockerfile . 

enclave-server-x86:
	docker build --build-arg TARGETPLATFORM=x86_64-unknown-linux-musl -t enclave-server -f Dockerfile . 
